-- migrate:up
CREATE TABLE transactions (
  transaction_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  transaction_user_id int REFERENCES users(user_id) NOT NULL,
  transaction_date_time timestamp DEFAULT now(),
  total_price money NOT NULL,
  tax numeric NOT NULL DEFAULT 0
);

CREATE INDEX transaction_user_id_fkey ON transactions (transaction_user_id)

-- migrate:down
DROP INDEX transaction_user_id_fkey;

DROP TABLE transactions;