-- migrate:up
CREATE TABLE users (
  user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_role_id int REFERENCES roles(role_id) NOT NULL,
  user_business_id int REFERENCES businesses(business_id),
  username text NOT NULL,
  password text NOT NULL,
  fname text NOT NULL,
  lname text NOT NULL,
  email text NOT NULL,
  is_verified boolean NOT NULL DEFAULT false
);

CREATE INDEX user_business_id_fkey ON users (user_business_id);

CREATE INDEX user_role_id_fkey ON users (user_role_id);

-- migrate:down
DROP INDEX user_business_id_fkey;

DROP INDEX user_role_id_fkey;

DROP TABLE users;