-- migrate:up
CREATE TABLE categories (
  category_code int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  category_name text NOT NULL,
  parent_category_code int REFERENCES categories(category_code)
);

CREATE INDEX parent_category_code_fkey ON categories (parent_category_code);

-- migrate:down
DROP INDEX parent_category_code;

DROP TABLE categories;
