-- migrate:up
CREATE TABLE parent_categories (
  category_code int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  category_name text NOT NULL
);

-- migrate:down
DROP TABLE parent_categories;
