-- migrate:up
CREATE TABLE purchases (
  purchase_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  purchase_user_id int REFERENCES users(user_id) NOT NULL,
  purchase_date_time timestamp DEFAULT now(),
  total_cost money NOT NULL DEFAULT 0
);

CREATE INDEX purchase_user_id_fkey ON purchases (purchase_user_id)

-- migrate:down
DROP INDEX purchase_user_id_fkey;

DROP TABLE purchases;