-- migrate:up
CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  role_id int REFERENCES roles(id) NOT NULL,
  business_id int REFERENCES businesses(id) NOT NULL,
  password text NOT NULL,
  fname text NOT NULL,
  lname text NOT NULL,
  email text NOT NULL,
  is_verified boolean DEFAULT false NOT NULL,
  verification_token text NOT NULL
);

CREATE INDEX business_id_fkey ON users (business_id);

CREATE INDEX role_id_fkey ON users (role_id);

-- migrate:down
DROP INDEX business_id_fkey;

DROP INDEX role_id_fkey;

DROP TABLE users;