-- migrate:up
CREATE TABLE restock_records (
  restock_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  item_code bigint REFERENCES items(item_code) NOT NULL,
  additional_qty int CHECK(additional_qty >= 0) NOT NULL,
  user_id int REFERENCES users(user_id) NOT NULL,
  restock_date_time timestamp DEFAULT now()
);

CREATE INDEX restock_item_code_fkey ON restock_records (item_code);

CREATE INDEX restock_user_id_fkey ON restock_records (user_id);

-- migrate:down
DROP INDEX restock_user_id_fkey;

DROP INDEX restock_item_code_fkey;

DROP TABLE restock_records;
