SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: businesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.businesses (
    business_id integer NOT NULL,
    business_name text NOT NULL
);


--
-- Name: businesses_business_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.businesses ALTER COLUMN business_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.businesses_business_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_transactions (
    transaction_id bigint NOT NULL,
    item_code integer NOT NULL,
    qty integer NOT NULL,
    total_price numeric NOT NULL
);


--
-- Name: items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.items (
    item_code integer NOT NULL,
    item_brand text NOT NULL,
    item_specs text NOT NULL,
    item_qty integer NOT NULL,
    item_unit_price numeric NOT NULL,
    item_unit text NOT NULL,
    reorder_point integer NOT NULL,
    CONSTRAINT items_item_qty_check CHECK ((item_qty >= 0))
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_title text NOT NULL,
    role_desc text NOT NULL
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying(255) NOT NULL
);


--
-- Name: transaction_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_records (
    transaction_id bigint NOT NULL
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    transaction_id bigint NOT NULL,
    transaction_user_id integer NOT NULL,
    transaction_date_time timestamp without time zone DEFAULT now(),
    transaction_payment numeric NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_role_id integer NOT NULL,
    user_business_id integer NOT NULL,
    password text NOT NULL,
    fname text NOT NULL,
    lname text NOT NULL,
    email text NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    verification_token text NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: businesses businesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.businesses
    ADD CONSTRAINT businesses_pkey PRIMARY KEY (business_id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (item_code);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: transaction_records transaction_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_records
    ADD CONSTRAINT transaction_records_pkey PRIMARY KEY (transaction_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: item_transactions_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX item_transactions_id_fkey ON public.item_transactions USING btree (transaction_id);


--
-- Name: transaction_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transaction_id_fkey ON public.transactions USING btree (transaction_id);


--
-- Name: transaction_user_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transaction_user_id_fkey ON public.transactions USING btree (transaction_user_id);


--
-- Name: user_business_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_business_id_fkey ON public.users USING btree (user_business_id);


--
-- Name: user_role_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_role_id_fkey ON public.users USING btree (user_role_id);


--
-- Name: item_transactions item_transactions_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_transactions
    ADD CONSTRAINT item_transactions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transaction_records(transaction_id);


--
-- Name: transactions transactions_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transaction_records(transaction_id);


--
-- Name: transactions transactions_transaction_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_transaction_user_id_fkey FOREIGN KEY (transaction_user_id) REFERENCES public.users(user_id);


--
-- Name: users users_user_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_business_id_fkey FOREIGN KEY (user_business_id) REFERENCES public.businesses(business_id);


--
-- Name: users users_user_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES public.roles(role_id);


--
-- PostgreSQL database dump complete
--


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20210105165730'),
    ('20210105165755'),
    ('20210105165810'),
    ('20210105165825'),
    ('20210105165921'),
    ('20210105165941'),
    ('20210105170211'),
    ('20210105170613');
