SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: businesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.businesses (
    business_id integer NOT NULL,
    business_name text NOT NULL
);


--
-- Name: businesses_business_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.businesses ALTER COLUMN business_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.businesses_business_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    category_code integer NOT NULL,
    category_name text NOT NULL
);


--
-- Name: categories_category_code_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN category_code ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    product_code integer NOT NULL,
    product_category_code integer NOT NULL,
    product_brand text NOT NULL,
    product_specs text NOT NULL,
    product_qty integer NOT NULL,
    product_unit_price money NOT NULL,
    product_unit text DEFAULT 'UNIT'::text NOT NULL,
    reorder_point integer DEFAULT 0 NOT NULL,
    CONSTRAINT products_product_qty_check CHECK ((product_qty >= 0))
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_title text NOT NULL,
    role_desc text NOT NULL
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying(255) NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_role_id integer NOT NULL,
    user_business_id integer NOT NULL,
    password text NOT NULL,
    fname text NOT NULL,
    lname text NOT NULL,
    email text NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    verification_token text NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: businesses businesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.businesses
    ADD CONSTRAINT businesses_pkey PRIMARY KEY (business_id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category_code);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_code);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: product_category_code_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX product_category_code_fkey ON public.products USING btree (product_category_code);


--
-- Name: user_business_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_business_id_fkey ON public.users USING btree (user_business_id);


--
-- Name: user_role_id_fkey; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_role_id_fkey ON public.users USING btree (user_role_id);


--
-- Name: products products_product_category_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_product_category_code_fkey FOREIGN KEY (product_category_code) REFERENCES public.categories(category_code);


--
-- Name: users users_user_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_business_id_fkey FOREIGN KEY (user_business_id) REFERENCES public.businesses(business_id);


--
-- Name: users users_user_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES public.roles(role_id);


--
-- PostgreSQL database dump complete
--


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20201129113101'),
    ('20201129113157'),
    ('20201129113321'),
    ('20201215021308'),
    ('20201215024525'),
    ('20201215025952');
